spring.application.name=${APP_NAME:BrilloCar}
server.port=${SERVER_PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/BrilloCar}
spring.datasource.username=${DB_USERNAME:yohan}
spring.datasource.password=${DB_PASSWORD:2748072}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
