spring.application.name=BrilloCar

spring.datasource.url=jdbc:postgresql://localhost:5432/BrilloCar
spring.datasource.username=yohan
spring.datasource.password=2748072
spring.datasource.driver-class-name=org.postgresql.Driver